### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by kongfei605** [huangtao00/QQ_for_CentOS7#1]
#运行run.sh 启动wine qq时，提示
$HOME/.deepinwine/Deepin-QQ/drive_c/deepin/EnvInit.sh:行22: /opt/deepinwine/tools/add_hotkeys: 没有那个文件或目录

少打包了一个add_hostkeys?

**Comment by huangtao00** [comment]
这个文件不是必须的,没有这个文件也能运行

**Comment by huangtao00** [comment]
@kongfei605 #1 这个文件不是必须的,不用管, 运行就行了
