### ISSUE TITLE
请教下楼主是如何解决摄像头问题的

### ISSUE THREAD

**Issue by lsblk** [huangtao00/QQ_for_CentOS7#4]
我是一名Arch用户，现在在用移植的deepinqq8.9，如果使用dde桌面的话，包括摄像头在内的所有功能都可以使用，但是gnome或kde就不行，我看到楼主在gnome上成功使用了摄像头，想问下楼主是如何解决的？

**Comment by huangtao00** [comment]
@lsblk 没有解决啊，我的笔记本上，摄像头也不能用！只能看到对方,说话对方也听不到！

**Comment by lsblk** [comment]
抱歉我看错了。。。打扰了
